# Medicare Data loaded, simplified, and saved to a csv file

The following notebook aims to do load data and do part of the preprocessing including to choose data related to medical costs and admissions. In reallity the code loads, formats data minimaly and saves it to an smaller file. 

For this part of the exploratory analysis I use government data from CMS – State/County Medicare Utilization Summary - https://www.cms.gov/Research-Statistics-Data-and-Systems/Statistics-Trends-and-Reports/Medicare-Geographic-Variation/GV_PUF 

My understanding of billing and healthcare system is limited. For this reason the variables chosen here are at my discretion. 

### Improvement:  
Import to a SQL df and query using python

In [1]:
# Import the necesary libraries
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import os

In [2]:
# Import the data 
path = os.path.join('assets','State County All Table 2019.xlsx')
df = pd.read_excel( path, encoding= "utf-8",head = None)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3252 entries, 0 to 3251
Columns: 248 entries, Unnamed: 0 to Unnamed: 247
dtypes: object(248)
memory usage: 6.2+ MB

In [3]:
df.head(5)

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Beneficiary Demographic Characteristics,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 238,Unnamed: 239,Unnamed: 240,Unnamed: 241,Unnamed: 242,Unnamed: 243,Unnamed: 244,Unnamed: 245,Unnamed: 246,Unnamed: 247
0,State,County,State and County FIPS Code,Beneficiaries with Part A and Part B,FFS Beneficiaries,MA Beneficiaries,MA Participation Rate,Average Age,Percent Female,Percent Male,...,PQI11 Bacterial Pneumonia Admission Rate (age ...,PQI11 Bacterial Pneumonia Admission Rate (age ...,PQI11 Bacterial Pneumonia Admission Rate (age ...,PQI12 UTI Admission Rate (age < 65),PQI12 UTI Admission Rate (age 65-74),PQI12 UTI Admission Rate (age 75+),PQI15 Asthma in Younger Adults Admission Rate ...,PQI16 Lower Extremity Amputation Admission Rat...,PQI16 Lower Extremity Amputation Admission Rat...,PQI16 Lower Extremity Amputation Admission Rat...
1,Na,NATIONAL TOTAL,NaN,42286251,32872694,9413557,22.26 %,72,56.15 %,43.85 %,...,981,815,2111,441,322,1234,420,124,49,55
2,AK,STATE TOTAL,NaN,53634,53203,431,0.80 %,70,50.93 %,49.07 %,...,853,858,1913,380,164,886,*,123,*,*
3,AK,Aleutians East,2013,69,69,0,0.00 %,70,40.58 %,59.42 %,...,,,,,,,,,,
4,AK,Aleutians West,2016,97,97,0,0.00 %,70,46.39 %,53.61 %,...,,,,,,,,,,

In [4]:
# full list of columns containing the data categories 
categories = df.columns.ravel()

In [5]:
categories

array(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2',
       'Beneficiary Demographic Characteristics', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8',
       'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12',
       'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15', 'Total Costs',
       'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20',
       'Unnamed: 21', 'Service-Level Costs and Utilization',
       'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Unnamed: 26',
       'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30',
       'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34',
       'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38',
       'Unnamed: 39', 'Unnamed: 40', 'Unnamed: 41', 'Unnamed: 42',
       'Unnamed: 43', 'Unnamed: 44', 'Unnamed: 45', 'Unnamed: 46',
       'Unnamed: 47', 'Unnamed: 48', 'Unnamed: 49', 'Unnamed: 50',
       'Unnamed: 51', 'Unnamed: 52', 'Unnamed: 53', 'Unnamed: 54',
       'Unnamed: 55', 'Unnamed: 56', 'Unnamed: 57', 'Unnamed: 58',
       'Unnamed: 59', 'Unnamed: 60', 'Unnamed: 61', 'Unnamed: 62',
       'Unnamed: 63', 'Unnamed: 64', 'Unnamed: 65', 'Unnamed: 66',
       'Unnamed: 67', 'Unnamed: 68', 'Unnamed: 69', 'Unnamed: 70',
       'Unnamed: 71', 'Unnamed: 72', 'Unnamed: 73', 'Unnamed: 74',
       'Unnamed: 75', 'Unnamed: 76', 'Unnamed: 77', 'Unnamed: 78',
       'Unnamed: 79', 'Unnamed: 80', 'Unnamed: 81', 'Unnamed: 82',
       'Unnamed: 83', 'Unnamed: 84', 'Unnamed: 85', 'Unnamed: 86',
       'Unnamed: 87', 'Unnamed: 88', 'Unnamed: 89', 'Unnamed: 90',
       'Unnamed: 91', 'Unnamed: 92', 'Unnamed: 93', 'Unnamed: 94',
       'Unnamed: 95', 'Unnamed: 96', 'Unnamed: 97', 'Unnamed: 98',
       'Unnamed: 99', 'Unnamed: 100', 'Unnamed: 101', 'Unnamed: 102',
       'Unnamed: 103', 'Unnamed: 104', 'Unnamed: 105', 'Unnamed: 106',
       'Unnamed: 107', 'Unnamed: 108', 'Unnamed: 109', 'Unnamed: 110',
       'Unnamed: 111', 'Unnamed: 112', 'Unnamed: 113', 'Unnamed: 114',
       'Unnamed: 115', 'Unnamed: 116', 'Unnamed: 117', 'Unnamed: 118',
       'Unnamed: 119', 'Unnamed: 120', 'Unnamed: 121', 'Unnamed: 122',
       'Unnamed: 123', 'Unnamed: 124', 'Unnamed: 125', 'Unnamed: 126',
       'Unnamed: 127', 'Unnamed: 128', 'Unnamed: 129', 'Unnamed: 130',
       'Unnamed: 131', 'Unnamed: 132', 'Unnamed: 133', 'Unnamed: 134',
       'Unnamed: 135', 'Unnamed: 136', 'Unnamed: 137', 'Unnamed: 138',
       'Unnamed: 139', 'Unnamed: 140', 'Unnamed: 141', 'Unnamed: 142',
       'Unnamed: 143', 'Unnamed: 144', 'Unnamed: 145', 'Unnamed: 146',
       'Unnamed: 147', 'Unnamed: 148', 'Unnamed: 149', 'Unnamed: 150',
       'Unnamed: 151', 'Unnamed: 152', 'Unnamed: 153', 'Unnamed: 154',
       'Unnamed: 155', 'Unnamed: 156', 'Unnamed: 157', 'Unnamed: 158',
       'Unnamed: 159', 'Unnamed: 160', 'Unnamed: 161', 'Unnamed: 162',
       'Unnamed: 163', 'Unnamed: 164', 'Unnamed: 165', 'Unnamed: 166',
       'Unnamed: 167', 'Unnamed: 168', 'Unnamed: 169', 'Unnamed: 170',
       'Unnamed: 171', 'Unnamed: 172', 'Unnamed: 173', 'Unnamed: 174',
       'Unnamed: 175', 'Unnamed: 176', 'Unnamed: 177', 'Unnamed: 178',
       'Unnamed: 179', 'Unnamed: 180', 'Unnamed: 181', 'Unnamed: 182',
       'Unnamed: 183', 'Unnamed: 184', 'Unnamed: 185', 'Unnamed: 186',
       'Unnamed: 187', 'Unnamed: 188', 'Unnamed: 189', 'Unnamed: 190',
       'Unnamed: 191', 'Unnamed: 192', 'Unnamed: 193', 'Unnamed: 194',
       'Unnamed: 195', 'Unnamed: 196', 'Unnamed: 197', 'Unnamed: 198',
       'Unnamed: 199', 'Unnamed: 200', 'Unnamed: 201', 'Unnamed: 202',
       'Unnamed: 203', 'Unnamed: 204', 'Unnamed: 205', 'Unnamed: 206',
       'Unnamed: 207', 'Unnamed: 208', 'Unnamed: 209', 'Unnamed: 210',
       'Unnamed: 211', 'Unnamed: 212', 'Unnamed: 213', 'Unnamed: 214',
       'Unnamed: 215', 'Unnamed: 216', 'Unnamed: 217', 'Unnamed: 218',
       'Unnamed: 219', 'Unnamed: 220', 'Unnamed: 221', 'Unnamed: 222',
       'Prevention Quality Indicators', 'Unnamed: 224', 'Unnamed: 225',
       'Unnamed: 226', 'Unnamed: 227', 'Unnamed: 228', 'Unnamed: 229',
       'Unnamed: 230', 'Unnamed: 231', 'Unnamed: 232', 'Unnamed: 233',
       'Unnamed: 234', 'Unnamed: 235', 'Unnamed: 236', 'Unnamed: 237',
       'Unnamed: 238', 'Unnamed: 239', 'Unnamed: 240', 'Unnamed: 241',
       'Unnamed: 242', 'Unnamed: 243', 'Unnamed: 244', 'Unnamed: 245',
       'Unnamed: 246', 'Unnamed: 247'], dtype=object)

In [6]:
df.head(5)

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Beneficiary Demographic Characteristics,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 238,Unnamed: 239,Unnamed: 240,Unnamed: 241,Unnamed: 242,Unnamed: 243,Unnamed: 244,Unnamed: 245,Unnamed: 246,Unnamed: 247
0,State,County,State and County FIPS Code,Beneficiaries with Part A and Part B,FFS Beneficiaries,MA Beneficiaries,MA Participation Rate,Average Age,Percent Female,Percent Male,...,PQI11 Bacterial Pneumonia Admission Rate (age ...,PQI11 Bacterial Pneumonia Admission Rate (age ...,PQI11 Bacterial Pneumonia Admission Rate (age ...,PQI12 UTI Admission Rate (age < 65),PQI12 UTI Admission Rate (age 65-74),PQI12 UTI Admission Rate (age 75+),PQI15 Asthma in Younger Adults Admission Rate ...,PQI16 Lower Extremity Amputation Admission Rat...,PQI16 Lower Extremity Amputation Admission Rat...,PQI16 Lower Extremity Amputation Admission Rat...
1,Na,NATIONAL TOTAL,NaN,42286251,32872694,9413557,22.26 %,72,56.15 %,43.85 %,...,981,815,2111,441,322,1234,420,124,49,55
2,AK,STATE TOTAL,NaN,53634,53203,431,0.80 %,70,50.93 %,49.07 %,...,853,858,1913,380,164,886,*,123,*,*
3,AK,Aleutians East,2013,69,69,0,0.00 %,70,40.58 %,59.42 %,...,,,,,,,,,,
4,AK,Aleutians West,2016,97,97,0,0.00 %,70,46.39 %,53.61 %,...,,,,,,,,,,

In [7]:
# set column labels to the first row and change column names
df.columns=df.iloc[0]
df.columns = df.columns.str.replace(' ', '_')
df = df.drop(df.index[0])

In [8]:
# full list of columns 
df.columns.ravel()

array(['State', 'County', 'State_and_County_FIPS_Code',
       'Beneficiaries_with_Part_A_and_Part_B', 'FFS_Beneficiaries',
       'MA_Beneficiaries', 'MA_Participation_Rate', 'Average_Age',
       'Percent_Female', 'Percent_Male', 'Percent_Non-Hispanic_White',
       'Percent_African_American', 'Percent_Hispanic',
       'Percent_Other/Unknown', 'Percent_Eligible_for_Medicaid',
       'Average_HCC_Score', 'Total_Actual_Costs',
       'Total_Standardized_Costs',
       'Total_Standardized_Risk-Adjusted_Costs',
       'Actual_Per_Capita_Costs', 'Standardized_Per_Capita_Costs',
       'Standardized_Risk-Adjusted_Per_Capita_Costs', 'IP_Actual_Costs',
       'IP_Actual_Costs_as_%_of_Total_Actual_Costs',
       'IP_Per_Capita_Actual_Costs', 'IP_Per_User_Actual_Costs',
       'IP_Standardized_Costs',
       'IP_Standardized_Costs_as_%_of_Total_Standardized_Costs',
       'IP_Per_Capita_Standardized_Costs',
       'IP_Per_User_Standardized_Costs', 'IP_Users_(with_a_covered_stay)',
       '%_of_Beneficiaries_Using_IP',
       'IP_Covered_Stays_Per_1000_Beneficiaries',
       'IP_Covered_Days_Per_1000_Beneficiaries',
       'Number_of_Acute_Hospital_Readmissions',
       'Hospital_Readmission_Rate', 'Emergency_Department_Visits',
       'Emergency_Department_Visits_per_1000_Beneficiaries',
       '%_of_Beneficiaries_with_an_ED_Visit', 'OP_Actual_Costs',
       'OP_Actual_Costs_as_%_of_Total_Actual_Costs',
       'OP_Per_Capita_Actual_Costs', 'OP_Per_User_Actual_Costs',
       'OP_Standardized_Costs',
       'OP_Standardized_Costs_as_%_of_Total_Standardized_Costs',
       'OP_Per_Capita_Standardized_Costs',
       'OP_Per_User_Standardized_Costs', '#_OP_Users',
       '%_of_Beneficiaries_Using_OP', 'OP_Visits_Per_1000_Beneficiaries',
       'ASC_Actual_Costs', 'ASC_Actual_Costs_as_%_of_Total_Actual_Costs',
       'ASC_Per_Capita_Actual_Costs', 'ASC_Per_User_Actual_Costs',
       'ASC_Standardized_Costs',
       'ASC_Standardized_Costs_as_%_of_Total_Standardized_Costs',
       'ASC_Per_Capita_Standardized_Costs',
       'ASC_Per_User_Standardized_Costs', '#_ASC_Users',
       '%_of_Beneficiaries_Using_ASC',
       'ASC_Events_Per_1000_Beneficiaries', 'PAC:_SNF_Actual_Costs',
       'PAC:_SNF_Actual_Costs_as_%_of_Total_Actual_Costs',
       'PAC:_SNF_Per_Capita_Actual_Costs',
       'PAC:_SNF_Per_User_Actual_Costs', 'PAC:_SNF_Standardized_Costs',
       'PAC:_SNF_Standardized_Costs_as_%_of_Total_Standardized_Costs',
       'PAC:_SNF_Per_Capita_Standardized_Costs',
       'PAC:_SNF_Per_User_Standardized_Costs',
       '#_PAC:_SNF_Users_(with_a_covered_stay)',
       '%_of_Beneficiaries_Using_PAC:_SNF',
       'PAC:_SNF_Covered_Stays_Per_1000_Beneficiaries',
       'PAC:_SNF_Covered_Days_Per_1000_Beneficiaries',
       'PAC:_IRF_Actual_Costs',
       'PAC:_IRF_Actual_Costs_as_%_of_Total_Actual_Costs',
       'PAC:_IRF_Per_Capita_Actual_Costs',
       'PAC:_IRF_Per_User_Actual_Costs', 'PAC:_IRF_Standardized_Costs',
       'PAC:_IRF_Standardized_Costs_as_%_of_Total_Standardized_Costs',
       'PAC:_IRF_Per_Capita_Standardized_Costs',
       'PAC:_IRF_Per_User_Standardized_Costs',
       '#_PAC:_IRF_Users_(with_a_covered_stay)',
       '%_of_Beneficiaries_Using_PAC:_IRF',
       'PAC:_IRF_Covered_Stays_Per_1000_Beneficiaries',
       'PAC:_IRF_Covered_Days_Per_1000_Beneficiaries',
       'PAC:_LTCH_Actual_Costs',
       'PAC:_LTCH_Actual_Costs_as_%_of_Total_Actual_Costs',
       'PAC:_LTCH_Per_Capita_Actual_Costs',
       'PAC:_LTCH_Per_User_Actual_Costs', 'PAC:_LTCH_Standardized_Costs',
       'PAC:_LTCH_Standardized_Costs_as_%_of_Total_Standardized_Costs',
       'PAC:_LTCH_Per_Capita_Standardized_Costs',
       'PAC:_LTCH_Per_User_Standardized_Costs',
       '#_PAC:_LTCH_Users_(with_a_covered_stay)',
       '%_of_Beneficiaries_Using_PAC:_LTCH',
       'PAC:_LTCH_Covered_Stays_Per_1000_Beneficiaries',
       'PAC:_LTCH_Covered_Days_Per_1000_Beneficiaries',
       'PAC:_HH_Actual_Costs',
       'PAC:_HH_Actual_Costs_as_%_of_Total_Actual_Costs',
       'PAC:_HH_Per_Capita_Actual_Costs', 'PAC:_HH_Per_User_Actual_Costs',
       'PAC:_HH_Standardized_Costs',
       'PAC:_HH_Standardized_Costs_as_%_of_Total_Standardized_Costs',
       'PAC:_HH_Per_Capita_Standardized_Costs',
       'PAC:_HH_Per_User_Standardized_Costs', '#_PAC:_HH_Users',
       '%_of_Beneficiaries_Using_PAC:_HH',
       'PAC:_HH_Episodes_Per_1000_Beneficiaries',
       'PAC:_HH_Visits_Per_1000_Beneficiaries', 'Hospice_Actual_Costs',
       'Hospice_Actual_Costs_as_%_of_Total_Actual_Costs',
       'Hospice_Per_Capita_Actual_Costs', 'Hospice_Per_User_Actual_Costs',
       'Hospice_Standardized_Costs',
       'Hospice_Standardized_Costs_as_%_of_Total_Standardized_Costs',
       'Hospice_Per_Capita_Standardized_Costs',
       'Hospice_Per_User_Standardized_Costs',
       '#_Hospice_Users_(with_a_covered_stay)',
       '%_of_Beneficiaries_Using_Hospice',
       'Hospice_Covered_Stays_Per_1000_Beneficiaries',
       'Hospice_Covered_Days_Per_1000_Beneficiaries', 'E&M_Actual_Costs',
       'E&M_Actual_Costs_as_%_of_Total_Actual_Costs',
       'E&M_Per_Capita_Actual_Costs', 'E&M_Per_User_Actual_Costs',
       'E&M_Standardized_Costs',
       'E&M_Standardized_Costs_as_%_of_Total_Standardized_Costs',
       'E&M_Per_Capita_Standardized_Costs',
       'E&M_Per_User_Standardized_Costs', '#_E&M_Users',
       '%_of_Beneficiaries_Using_E&M',
       'E&M_Events_Per_1000_Beneficiaries', 'Procedures_Actual_Costs',
       'Procedures_Actual_Costs_as_%_of_Total_Actual_Costs',
       'Procedures_Per_Capita_Actual_Costs',
       'Procedures_Per_User_Actual_Costs',
       'Procedures_Standardized_Costs',
       'Procedures_Standardized_Costs_as_%_of_Total_Standardized_Costs',
       'Procedures_Per_Capita_Standardized_Costs',
       'Procedures_Per_User_Standardized_Costs', '#_Procedure_Users',
       '%_of_Beneficiaries_Using_Procedures',
       'Procedure_Events_Per_1000_Beneficiaries', 'Tests_Actual_Costs',
       'Tests_Actual_Costs_as_%_of_Total_Actual_Costs',
       'Tests_Per_Capita_Actual_Costs', 'Tests_Per_User_Actual_Costs',
       'Tests_Standardized_Costs',
       'Tests_Standardized_Costs_as_%_of_Total_Standardized_Costs',
       'Tests_Per_Capita_Standardized_Costs',
       'Tests_Per_User_Standardized_Costs', '#_Test_Users',
       '%_of_Beneficiaries_Using_Tests',
       'Test_Events_Per_1000_Beneficiaries', 'Imaging_Actual_Costs',
       'Imaging_Actual_Costs_as_%_of_Total_Actual_Costs',
       'Imaging_Per_Capita_Actual_Costs', 'Imaging_Per_User_Actual_Costs',
       'Imaging_Standardized_Costs',
       'Imaging_Standardized_Costs_as_%_of_Total_Standardized_Costs',
       'Imaging_Per_Capita_Standardized_Costs',
       'Imaging_Per_User_Standardized_Costs', '#_Imaging_Users',
       '%_of_Beneficiaries_Using_Imaging',
       'Imaging_Events_Per_1000_Beneficiaries', 'DME_Actual_Costs',
       'DME_Actual_Costs_as_%_of_Total_Actual_Costs',
       'DME_Per_Capita_Actual_Costs', 'DME_Per_User_Actual_Costs',
       'DME_Standardized_Costs',
       'DME_Standardized_Costs_as_%_of_Total_Standardized_Costs',
       'DME_Per_Capita_Standardized_Costs',
       'DME_Per_User_Standardized_Costs', '#_DME_Users',
       '%_of_Beneficiaries_Using_DME',
       'DME_Events_Per_1000_Beneficiaries',
       'Outpatient_Dialysis_Facility_Actual_Costs',
       'Outpatient_Dialysis_Facility_Actual_Costs_as_%_of_Total_Actual_Costs',
       'Outpatient_Dialysis_Facility_Per_Capita_Actual_Costs',
       'Outpatient_Dialysis_Facility_Per_User_Actual_Costs',
       'Outpatient_Dialysis_Facility_Standardized_Costs',
       'Outpatient_Dialysis_Facility_Standardized_Costs_as_%_of_Total_Standardized_Costs',
       'Outpatient_Dialysis_Facility_Per_Capita_Standardized_Costs',
       'Outpatient_Dialysis_Facility_Per_User_Standardized_Costs',
       '#_Outpatient_Dialysis_Facility_Users',
       '%_of_Beneficiaries_Using_Outpatient_Dialysis_Facility',
       'Outpatient_Dialysis_Facility_Events_Per_1000_Beneficiaries',
       'FQHC/RHC_Actual_Costs',
       'FQHC/RHC_Actual_Costs_as_%_of_Total_Actual_Costs',
       'FQHC/RHC_Per_Capita_Actual_Costs',
       'FQHC/RHC_Per_User_Actual_Costs', 'FQHC/RHC_Standardized_Costs',
       'FQHC/RHC_Standardized_Costs_as_%_of_Total_Standardized_Costs',
       'FQHC/RHC_Per_Capita_Standardized_Costs',
       'FQHC/RHC_Per_User_Standardized_Costs', '#_FQHC/RHC_Users',
       '%_of_Beneficiaries_Using_FQHC/RHC',
       'FQHC/RHC_Visits_Per_1000_Beneficiaries', 'Ambulance_Actual_Costs',
       'Ambulance_Actual_Costs_as_%_of_Total_Actual_Costs',
       'Ambulance_Per_Capita_Actual_Costs',
       'Ambulance_Per_User_Actual_Costs', 'Ambulance_Standardized_Costs',
       'Ambulance_Standardized_Costs_as_%_of_Total_Standardized_Costs',
       'Ambulance_Per_Capita_Standardized_Costs',
       'Ambulance_Per_User_Standardized_Costs', '#_Ambulance_Users',
       '%_of_Beneficiaries_Using_Ambulance',
       'Ambulance_Events_Per_1000_Beneficiaries',
       'Part_B_Drugs_Actual_Costs',
       'Part_B_Drugs_Actual_Costs_as_%_of_Total_Actual_Costs',
       'Part_B_Drugs_Per_Capita_Actual_Costs',
       'Part_B_Drugs_Per_User_Actual_Costs',
       'Part_B_Drugs_Standardized_Costs',
       'Part_B_Drugs_Standardized_Costs_as_%_of_Total_Standardized_Costs',
       'Part_B_Drugs_Per_Capita_Standardized_Costs',
       'Part_B_Drugs_Per_User_Standardized_Costs', '#_Part_B_Drugs_Users',
       '%_of_Beneficiaries_Using_Part_B_Drugs',
       'Other_Services_Actual_Costs', 'Other_Services_Standardized_Costs',
       'Total_Population_Based_Payment_Reduction_Costs',
       'Total_Population_Based_Payment_Reduction_Per_Capita_Costs',
       'PQI03_Diabetes_LT_Complication_Admission_Rate_(age_<_65)',
       'PQI03_Diabetes_LT_Complication_Admission_Rate_(age_65-74)',
       'PQI03_Diabetes_LT_Complication_Admission_Rate_(age_75+)',
       'PQI05_COPD_or_Asthma_in_Older_Adults_Admission_Rate_(age_40-64)',
       'PQI05_COPD_or_Asthma_in_Older_Adults_Admission_Rate_(age_65-74)',
       'PQI05_COPD_or_Asthma_in_Older_Adults_Admission_Rate_(age_75+)',
       'PQI07_Hypertension_Admission_Rate_(age_<_65)',
       'PQI07_Hypertension_Admission_Rate_(age_65-74)',
       'PQI07_Hypertension_Admission_Rate_(age_75+)',
       'PQI08_CHF_Admission_Rate_(age_<_65)',
       'PQI08_CHF_Admission_Rate_(age_65-74)',
       'PQI08_CHF_Admission_Rate_(age_75+)',
       'PQI10_Dehydration_Admission_Rate_(age_<_65)',
       'PQI10_Dehydration_Admission_Rate_(age_65-74)',
       'PQI10_Dehydration_Admission_Rate_(age_75+)',
       'PQI11_Bacterial_Pneumonia_Admission_Rate_(age_<_65)',
       'PQI11_Bacterial_Pneumonia_Admission_Rate_(age_65-74)',
       'PQI11_Bacterial_Pneumonia_Admission_Rate_(age_75+)',
       'PQI12_UTI_Admission_Rate_(age_<_65)',
       'PQI12_UTI_Admission_Rate_(age_65-74)',
       'PQI12_UTI_Admission_Rate_(age_75+)',
       'PQI15_Asthma_in_Younger_Adults_Admission_Rate_(age_<_40)',
       'PQI16_Lower_Extremity_Amputation_Admission_Rate_(age_<_65)',
       'PQI16_Lower_Extremity_Amputation_Admission_Rate_(age_65-74)',
       'PQI16_Lower_Extremity_Amputation_Admission_Rate_(age_75+)'],
      dtype=object)

In [9]:
df.head()

,State,County,State_and_County_FIPS_Code,Beneficiaries_with_Part_A_and_Part_B,FFS_Beneficiaries,MA_Beneficiaries,MA_Participation_Rate,Average_Age,Percent_Female,Percent_Male,...,PQI11_Bacterial_Pneumonia_Admission_Rate_(age_<_65),PQI11_Bacterial_Pneumonia_Admission_Rate_(age_65-74),PQI11_Bacterial_Pneumonia_Admission_Rate_(age_75+),PQI12_UTI_Admission_Rate_(age_<_65),PQI12_UTI_Admission_Rate_(age_65-74),PQI12_UTI_Admission_Rate_(age_75+),PQI15_Asthma_in_Younger_Adults_Admission_Rate_(age_<_40),PQI16_Lower_Extremity_Amputation_Admission_Rate_(age_<_65),PQI16_Lower_Extremity_Amputation_Admission_Rate_(age_65-74),PQI16_Lower_Extremity_Amputation_Admission_Rate_(age_75+)
1,Na,NATIONAL TOTAL,NaN,42286251,32872694,9413557,22.26 %,72,56.15 %,43.85 %,...,981,815,2111,441,322,1234,420,124,49,55
2,AK,STATE TOTAL,NaN,53634,53203,431,0.80 %,70,50.93 %,49.07 %,...,853,858,1913,380,164,886,*,123,*,*
3,AK,Aleutians East,2013,69,69,0,0.00 %,70,40.58 %,59.42 %,...,,,,,,,,,,
4,AK,Aleutians West,2016,97,97,0,0.00 %,70,46.39 %,53.61 %,...,,,,,,,,,,
5,AK,Anchorage,2020,21145,20963,182,0.86 %,69,53.54 %,46.46 %,...,,,,,,,,,,

Data Cleaning & Exploring 

The first step in pipeline after importing data is cleaning and data exploration.
First we need to consider which variables are at the county level and withch ones are only at the State level. 'Prevention Quality Indicators' are at national and state level NOT county level 
For the analysis at county level these variables will not be considered further

In [10]:
#'Beneficiary Demographic Characteristics' and 'Service-Level Costs and Utilization'
# are at national, state level, and county level 
#'Prevention Quality Indicators' are at national and state level NOT county level 
# For the analysis at county level these variables will not be considered further

location = df.columns[0:3].to_list()
demographics = df.columns[3:22].to_list()
prevention = df.columns[22:223].to_list()

columns = location + demographics + prevention

df1 = df.loc[:, columns] 
df1.head()

,State,County,State_and_County_FIPS_Code,Beneficiaries_with_Part_A_and_Part_B,FFS_Beneficiaries,MA_Beneficiaries,MA_Participation_Rate,Average_Age,Percent_Female,Percent_Male,...,Part_B_Drugs_Standardized_Costs,Part_B_Drugs_Standardized_Costs_as_%_of_Total_Standardized_Costs,Part_B_Drugs_Per_Capita_Standardized_Costs,Part_B_Drugs_Per_User_Standardized_Costs,#_Part_B_Drugs_Users,%_of_Beneficiaries_Using_Part_B_Drugs,Other_Services_Actual_Costs,Other_Services_Standardized_Costs,Total_Population_Based_Payment_Reduction_Costs,Total_Population_Based_Payment_Reduction_Per_Capita_Costs
1,Na,NATIONAL TOTAL,NaN,42286251,32872694,9413557,22.26 %,72,56.15 %,43.85 %,...,8.94199e+09,3.39 %,272.02,529.58,16884971,51.36 %,3.7934e+09,3.94884e+09,,
2,AK,STATE TOTAL,NaN,53634,53203,431,0.80 %,70,50.93 %,49.07 %,...,9.67064e+06,3.27 %,181.77,555.88,17397,32.70 %,2.39546e+06,2.41003e+06,,
3,AK,Aleutians East,2013,69,69,0,0.00 %,70,40.58 %,59.42 %,...,2397.04,1.08 %,34.74,171.22,14,20.29 %,*,*,,
4,AK,Aleutians West,2016,97,97,0,0.00 %,70,46.39 %,53.61 %,...,*,*,*,*,*,*,8978.6,9071.61,,
5,AK,Anchorage,2020,21145,20963,182,0.86 %,69,53.54 %,46.46 %,...,5.04373e+06,4.34 %,240.6,609.59,8274,39.47 %,834902,845413,,

In [ ]:
#'Prevention Quality Indicators' are at national and state level NOT county level 
# For the analysis at county level it is not usefull
# location = df.columns[0:3].to_list()
# prevention = df.columns[223:248].to_list()

# columns = location + prevention

# df_prevention = df.loc[:, columns] 
# df_prevention.head()

In [11]:
# hard copy dataframe
df2 = df1.copy()

In [12]:
df2.head(10)

,State,County,State_and_County_FIPS_Code,Beneficiaries_with_Part_A_and_Part_B,FFS_Beneficiaries,MA_Beneficiaries,MA_Participation_Rate,Average_Age,Percent_Female,Percent_Male,...,Part_B_Drugs_Standardized_Costs,Part_B_Drugs_Standardized_Costs_as_%_of_Total_Standardized_Costs,Part_B_Drugs_Per_Capita_Standardized_Costs,Part_B_Drugs_Per_User_Standardized_Costs,#_Part_B_Drugs_Users,%_of_Beneficiaries_Using_Part_B_Drugs,Other_Services_Actual_Costs,Other_Services_Standardized_Costs,Total_Population_Based_Payment_Reduction_Costs,Total_Population_Based_Payment_Reduction_Per_Capita_Costs
1,Na,NATIONAL TOTAL,NaN,42286251,32872694,9413557,22.26 %,72,56.15 %,43.85 %,...,8.94199e+09,3.39 %,272.02,529.58,16884971,51.36 %,3.7934e+09,3.94884e+09,,
2,AK,STATE TOTAL,NaN,53634,53203,431,0.80 %,70,50.93 %,49.07 %,...,9.67064e+06,3.27 %,181.77,555.88,17397,32.70 %,2.39546e+06,2.41003e+06,,
3,AK,Aleutians East,2013,69,69,0,0.00 %,70,40.58 %,59.42 %,...,2397.04,1.08 %,34.74,171.22,14,20.29 %,*,*,,
4,AK,Aleutians West,2016,97,97,0,0.00 %,70,46.39 %,53.61 %,...,*,*,*,*,*,*,8978.6,9071.61,,
5,AK,Anchorage,2020,21145,20963,182,0.86 %,69,53.54 %,46.46 %,...,5.04373e+06,4.34 %,240.6,609.59,8274,39.47 %,834902,845413,,
6,AK,Bethel,2050,881,881,0,0.00 %,71,50.62 %,49.38 %,...,2107.76,0.06 %,2.39,175.65,12,1.36 %,*,*,,
7,AK,Bristol Bay,2060,*,96,*,*,70,50.00 %,50.00 %,...,931.07,0.22 %,9.7,49,19,19.79 %,*,*,,
8,AK,Denali,2068,*,119,*,*,67,44.54 %,55.46 %,...,14494.2,4.86 %,121.8,452.94,32,26.89 %,*,*,,
9,AK,Dillingham,2070,323,323,0,0.00 %,71,49.54 %,50.46 %,...,3022.98,0.11 %,9.36,188.94,16,4.95 %,*,*,,
10,AK,Fairbanks North Star,2090,6139,6100,39,0.64 %,70,49.30 %,50.70 %,...,2.09716e+06,6.86 %,343.8,1028.53,2039,33.43 %,142562,140766,,

### Cleaning data

Rename columns. Replace symbols. Remove NaN data from FIPS because corresponds to rows with data at the State level.
Remove % symbols and transform to proper numerical formats.

In [13]:
# rename 
df2 = df2.rename(columns ={'State_and_County_FIPS_Code':'FIPS'})
# replace *
df1 = df1.replace("*","")

In [14]:
# remove data NaN at the National and State level
df2 = df2.dropna(subset=['FIPS'])
df2.head()

,State,County,FIPS,Beneficiaries_with_Part_A_and_Part_B,FFS_Beneficiaries,MA_Beneficiaries,MA_Participation_Rate,Average_Age,Percent_Female,Percent_Male,...,Part_B_Drugs_Standardized_Costs,Part_B_Drugs_Standardized_Costs_as_%_of_Total_Standardized_Costs,Part_B_Drugs_Per_Capita_Standardized_Costs,Part_B_Drugs_Per_User_Standardized_Costs,#_Part_B_Drugs_Users,%_of_Beneficiaries_Using_Part_B_Drugs,Other_Services_Actual_Costs,Other_Services_Standardized_Costs,Total_Population_Based_Payment_Reduction_Costs,Total_Population_Based_Payment_Reduction_Per_Capita_Costs
3,AK,Aleutians East,2013,69,69,0,0.00 %,70,40.58 %,59.42 %,...,2397.04,1.08 %,34.74,171.22,14,20.29 %,*,*,,
4,AK,Aleutians West,2016,97,97,0,0.00 %,70,46.39 %,53.61 %,...,*,*,*,*,*,*,8978.6,9071.61,,
5,AK,Anchorage,2020,21145,20963,182,0.86 %,69,53.54 %,46.46 %,...,5.04373e+06,4.34 %,240.6,609.59,8274,39.47 %,834902,845413,,
6,AK,Bethel,2050,881,881,0,0.00 %,71,50.62 %,49.38 %,...,2107.76,0.06 %,2.39,175.65,12,1.36 %,*,*,,
7,AK,Bristol Bay,2060,*,96,*,*,70,50.00 %,50.00 %,...,931.07,0.22 %,9.7,49,19,19.79 %,*,*,,

In [15]:
for (columnName, columnData) in df2.iteritems():
    if columnName != 'State' and columnName != 'County':
        splitName = columnName.split("_")
  
        if 'Percent' in splitName:
            df2[columnName] = df2[columnName].str.split(" ", n = 1, expand = True)[0]
        elif 'Rate' in splitName:
            df2[columnName] = df2[columnName].str.split(" ", n = 1, expand = True)[0]
        elif '%' in splitName:
            df2[columnName] = df2[columnName].str.split(" ", n = 1, expand = True)[0]

        df2[columnName] = pd.to_numeric(df2[columnName], errors='coerce')


df2.head(20)

,State,County,FIPS,Beneficiaries_with_Part_A_and_Part_B,FFS_Beneficiaries,MA_Beneficiaries,MA_Participation_Rate,Average_Age,Percent_Female,Percent_Male,...,Part_B_Drugs_Standardized_Costs,Part_B_Drugs_Standardized_Costs_as_%_of_Total_Standardized_Costs,Part_B_Drugs_Per_Capita_Standardized_Costs,Part_B_Drugs_Per_User_Standardized_Costs,#_Part_B_Drugs_Users,%_of_Beneficiaries_Using_Part_B_Drugs,Other_Services_Actual_Costs,Other_Services_Standardized_Costs,Total_Population_Based_Payment_Reduction_Costs,Total_Population_Based_Payment_Reduction_Per_Capita_Costs
3,AK,Aleutians East,2013,69.0,69.0,0.0,0.00,70.0,40.58,59.42,...,2397.04,1.08,34.74,171.22,14.0,20.29,NaN,NaN,NaN,NaN
4,AK,Aleutians West,2016,97.0,97.0,0.0,0.00,70.0,46.39,53.61,...,NaN,NaN,NaN,NaN,NaN,NaN,8978.60,9071.61,NaN,NaN
5,AK,Anchorage,2020,21145.0,20963.0,182.0,0.86,69.0,53.54,46.46,...,5043727.86,4.34,240.60,609.59,8274.0,39.47,834901.93,845413.18,NaN,NaN
6,AK,Bethel,2050,881.0,881.0,0.0,0.00,71.0,50.62,49.38,...,2107.76,0.06,2.39,175.65,12.0,1.36,NaN,NaN,NaN,NaN
7,AK,Bristol Bay,2060,NaN,96.0,NaN,NaN,70.0,50.00,50.00,...,931.07,0.22,9.70,49.00,19.0,19.79,NaN,NaN,NaN,NaN
8,AK,Denali,2068,NaN,119.0,NaN,NaN,67.0,44.54,55.46,...,14494.17,4.86,121.80,452.94,32.0,26.89,NaN,NaN,NaN,NaN
9,AK,Dillingham,2070,323.0,323.0,0.0,0.00,71.0,49.54,50.46,...,3022.98,0.11,9.36,188.94,16.0,4.95,NaN,NaN,NaN,NaN
10,AK,Fairbanks North Star,2090,6139.0,6100.0,39.0,0.64,70.0,49.30,50.70,...,2097163.45,6.86,343.80,1028.53,2039.0,33.43,142561.86,140765.70,NaN,NaN
11,AK,Haines,2100,NaN,358.0,NaN,NaN,71.0,48.04,51.96,...,97137.81,7.00,271.33,3035.56,32.0,8.94,14517.52,14061.55,NaN,NaN
12,AK,Hoonah-Angoon,2105,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,AK,Juneau,2110,2679.0,2664.0,15.0,0.56,70.0,53.90,46.10,...,202419.76,1.38,75.98,196.72,1029.0,38.63,149497.75,148870.02,NaN,NaN
14,AK,Kenai Peninsula,2122,6170.0,6097.0,73.0,1.18,70.0,49.07,50.93,...,610244.14,1.89,100.09,304.97,2001.0,32.82,449305.00,450927.66,NaN,NaN
15,AK,Ketchikan Gateway,2130,NaN,1511.0,NaN,NaN,70.0,50.43,49.57,...,118451.75,1.13,78.39,372.49,318.0,21.05,73634.13,72551.61,NaN,NaN
16,AK,Kodiak Island,2150,NaN,825.0,NaN,NaN,70.0,47.88,52.12,...,78412.79,1.37,95.05,252.13,311.0,37.70,54515.07,52225.75,NaN,NaN
17,AK,Lake and Peninsula,2164,NaN,103.0,NaN,NaN,72.0,44.66,55.34,...,2489.18,0.62,24.17,191.48,13.0,12.62,NaN,NaN,NaN,NaN
18,AK,Matanuska-Susitna,2170,6660.0,6581.0,79.0,1.19,69.0,49.60,50.40,...,882724.22,2.47,134.13,383.29,2303.0,34.99,241975.88,249842.57,NaN,NaN
19,AK,Nome,2180,NaN,561.0,NaN,NaN,71.0,48.13,51.87,...,9472.38,0.27,16.88,430.56,22.0,3.92,33374.95,33196.58,NaN,NaN
20,AK,North Slope,2185,NaN,340.0,NaN,NaN,71.0,51.18,48.82,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,AK,Northwest Arctic,2188,366.0,366.0,0.0,0.00,72.0,50.27,49.73,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,AK,Prince of Wales-Outer Ket,2201,NaN,519.0,NaN,NaN,69.0,42.00,58.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
check= df2['IP_Actual_Costs']
check.head(20)

3       213506.86
4       427616.36
5     67348037.26
6      3368118.22
7       302929.37
8             NaN
9      1930983.40
10    17519533.83
11      863935.99
12            NaN
13     8685651.40
14    19021025.61
15     5045866.32
16     2993059.30
17      416065.70
18    18999370.10
19     2656091.15
20     2220495.16
21     2604612.01
22            NaN
Name: IP_Actual_Costs, dtype: float64

In [18]:
df2 = df2.dropna(subset=['IP_Actual_Costs'])

In [19]:
df2.head(20)

,State,County,FIPS,Beneficiaries_with_Part_A_and_Part_B,FFS_Beneficiaries,MA_Beneficiaries,MA_Participation_Rate,Average_Age,Percent_Female,Percent_Male,...,Part_B_Drugs_Standardized_Costs,Part_B_Drugs_Standardized_Costs_as_%_of_Total_Standardized_Costs,Part_B_Drugs_Per_Capita_Standardized_Costs,Part_B_Drugs_Per_User_Standardized_Costs,#_Part_B_Drugs_Users,%_of_Beneficiaries_Using_Part_B_Drugs,Other_Services_Actual_Costs,Other_Services_Standardized_Costs,Total_Population_Based_Payment_Reduction_Costs,Total_Population_Based_Payment_Reduction_Per_Capita_Costs
3,AK,Aleutians East,2013,69.0,69.0,0.0,0.00,70.0,40.58,59.42,...,2397.04,1.08,34.74,171.22,14.0,20.29,NaN,NaN,NaN,NaN
4,AK,Aleutians West,2016,97.0,97.0,0.0,0.00,70.0,46.39,53.61,...,NaN,NaN,NaN,NaN,NaN,NaN,8978.60,9071.61,NaN,NaN
5,AK,Anchorage,2020,21145.0,20963.0,182.0,0.86,69.0,53.54,46.46,...,5043727.86,4.34,240.60,609.59,8274.0,39.47,834901.93,845413.18,NaN,NaN
6,AK,Bethel,2050,881.0,881.0,0.0,0.00,71.0,50.62,49.38,...,2107.76,0.06,2.39,175.65,12.0,1.36,NaN,NaN,NaN,NaN
7,AK,Bristol Bay,2060,NaN,96.0,NaN,NaN,70.0,50.00,50.00,...,931.07,0.22,9.70,49.00,19.0,19.79,NaN,NaN,NaN,NaN
9,AK,Dillingham,2070,323.0,323.0,0.0,0.00,71.0,49.54,50.46,...,3022.98,0.11,9.36,188.94,16.0,4.95,NaN,NaN,NaN,NaN
10,AK,Fairbanks North Star,2090,6139.0,6100.0,39.0,0.64,70.0,49.30,50.70,...,2097163.45,6.86,343.80,1028.53,2039.0,33.43,142561.86,140765.70,NaN,NaN
11,AK,Haines,2100,NaN,358.0,NaN,NaN,71.0,48.04,51.96,...,97137.81,7.00,271.33,3035.56,32.0,8.94,14517.52,14061.55,NaN,NaN
13,AK,Juneau,2110,2679.0,2664.0,15.0,0.56,70.0,53.90,46.10,...,202419.76,1.38,75.98,196.72,1029.0,38.63,149497.75,148870.02,NaN,NaN
14,AK,Kenai Peninsula,2122,6170.0,6097.0,73.0,1.18,70.0,49.07,50.93,...,610244.14,1.89,100.09,304.97,2001.0,32.82,449305.00,450927.66,NaN,NaN
15,AK,Ketchikan Gateway,2130,NaN,1511.0,NaN,NaN,70.0,50.43,49.57,...,118451.75,1.13,78.39,372.49,318.0,21.05,73634.13,72551.61,NaN,NaN
16,AK,Kodiak Island,2150,NaN,825.0,NaN,NaN,70.0,47.88,52.12,...,78412.79,1.37,95.05,252.13,311.0,37.70,54515.07,52225.75,NaN,NaN
17,AK,Lake and Peninsula,2164,NaN,103.0,NaN,NaN,72.0,44.66,55.34,...,2489.18,0.62,24.17,191.48,13.0,12.62,NaN,NaN,NaN,NaN
18,AK,Matanuska-Susitna,2170,6660.0,6581.0,79.0,1.19,69.0,49.60,50.40,...,882724.22,2.47,134.13,383.29,2303.0,34.99,241975.88,249842.57,NaN,NaN
19,AK,Nome,2180,NaN,561.0,NaN,NaN,71.0,48.13,51.87,...,9472.38,0.27,16.88,430.56,22.0,3.92,33374.95,33196.58,NaN,NaN
20,AK,North Slope,2185,NaN,340.0,NaN,NaN,71.0,51.18,48.82,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,AK,Northwest Arctic,2188,366.0,366.0,0.0,0.00,72.0,50.27,49.73,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,AK,Sitka,2220,NaN,878.0,NaN,NaN,72.0,52.62,47.38,...,32652.80,0.52,37.19,174.61,187.0,21.30,38081.35,38506.54,NaN,NaN
25,AK,Skagway-Hoonah-Angoon,2232,NaN,333.0,NaN,NaN,71.0,47.45,52.55,...,20291.04,1.66,60.93,289.87,70.0,21.02,NaN,NaN,NaN,NaN
26,AK,Southeast Fairbanks,2240,NaN,709.0,NaN,NaN,70.0,42.88,57.12,...,144442.95,4.41,203.73,662.58,218.0,30.75,13281.88,13108.99,NaN,NaN

In [ ]:
df2.info()

In [20]:
# Save data

df2.to_csv('assets/data_cost_df2.csv', index=False, header=True)